name = "Gensokyo Reimagined QOL"
author = "Taiyou06"
version = "1.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8b7f3eefa87e84b280055d8e0721a0b9088c1ee8fa6117d81716d6b238c3fb7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
