name = "Gensokyo Reimagined QOL"
author = "Taiyou06"
version = "1.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a227cde8479b0bde774037ebe80c942ab7b60352e2c65fc705793fab0fb54019"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
