name = "Gensokyo Reimagined QOL"
author = "Taiyou06"
version = "1.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e92a6024984cd0d2458778595967726fd420966a9a0aacd3ffa26c171cb7daf1"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
