name = "Gensokyo Reimagined QOL"
author = "Taiyou06"
version = "1.11.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7df1967ab39f15db947b031325628175ff321e00a5bf791a3e2ee6ceb16d3ec"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"
