name = "Gensokyo Reimagined QOL"
author = "Taiyou06"
version = "1.12.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "686ba6b7050e5bf4c64d5ea7dfdfe5c9cdef2fa3e3ebb6e546dc3d4e311ae60a"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
