name = "Gensokyo Reimagined QOL"
author = "Taiyou06"
version = "1.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "065c400a66bd2af27e214b0114d655c4258adb87af770aa0a869486371fd9c26"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
