name = "Gensokyo Reimagined QOL"
author = "Taiyou06"
version = "1.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa3c787180f3324cd97d84ecb81e437bbc23102a9427c7858ba63f27ca237ae9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
